services:
  app:
    build: ./backend
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./frontend:/frontend:ro
    ports:
      - "8080:8000"
    environment:
      - TZ=Europe/Vienna
